services:
  asterdrive:
    # build: .
    image: ghcr.io/apts-1547/asterdrive:latest
    ports:
      - "3000:3000"
    volumes:
      - asterdrive-data:/data
      - /etc/localtime:/etc/localtime:ro
      - ./config.toml:/data/config.toml:ro
    environment:
      - ASTER__SERVER__HOST=0.0.0.0
      - ASTER__DATABASE__URL=sqlite:///data/asterdrive.db?mode=rwc
    restart: unless-stopped

volumes:
  asterdrive-data:
