/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/config/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_config"];
        put: operations["set_config"];
        post?: never;
        delete: operations["delete_config"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_policies"];
        put?: never;
        post: operations["create_policy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/policies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_policy"];
        put?: never;
        post?: never;
        delete: operations["delete_policy"];
        options?: never;
        head?: never;
        patch: operations["update_policy"];
        trace?: never;
    };
    "/api/v1/admin/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_all_shares"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/shares/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["admin_delete_share"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_user"];
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_user_policies"];
        put?: never;
        post: operations["assign_user_policy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/policies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["remove_user_policy"];
        options?: never;
        head?: never;
        patch: operations["update_user_policy"];
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["upload_file"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/upload/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["init_chunked_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/upload/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_upload_progress"];
        put?: never;
        post?: never;
        delete: operations["cancel_upload"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/upload/{upload_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["complete_chunked_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/upload/{upload_id}/{chunk_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["upload_chunk"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_file"];
        put?: never;
        post?: never;
        delete: operations["delete_file"];
        options?: never;
        head?: never;
        patch: operations["patch_file"];
        trace?: never;
    };
    "/api/v1/files/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["download_file"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_thumbnail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_root"];
        put?: never;
        post: operations["create_folder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/folders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_folder"];
        put?: never;
        post?: never;
        delete: operations["delete_folder"];
        options?: never;
        head?: never;
        patch: operations["patch_folder"];
        trace?: never;
    };
    "/api/v1/s/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_share_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/s/{token}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_shared_content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/s/{token}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["download_shared_file"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/s/{token}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verify_share_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_my_shares"];
        put?: never;
        post: operations["create_share"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shares/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_share"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webdav-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_webdav_accounts"];
        put?: never;
        post: operations["create_webdav_account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webdav-accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_webdav_account"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webdav-accounts/{id}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["toggle_webdav_account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AssignUserPolicyReq: {
            is_default?: boolean;
            /** Format: int64 */
            policy_id: number;
            /** Format: int64 */
            quota_bytes?: number;
        };
        ChunkUploadResponse: {
            /** Format: int32 */
            received_count: number;
            /** Format: int32 */
            total_chunks: number;
        };
        CreateFolderReq: {
            name: string;
            /** Format: int64 */
            parent_id?: number | null;
        };
        CreatePolicyReq: {
            access_key?: string | null;
            base_path?: string | null;
            bucket?: string | null;
            /** Format: int64 */
            chunk_size?: number | null;
            driver_type: components["schemas"]["DriverType"];
            endpoint?: string | null;
            is_default?: boolean | null;
            /** Format: int64 */
            max_file_size?: number | null;
            name: string;
            secret_key?: string | null;
        };
        CreateShareReq: {
            expires_at?: string | null;
            /** Format: int64 */
            file_id?: number | null;
            /** Format: int64 */
            folder_id?: number | null;
            /** Format: int64 */
            max_downloads?: number;
            password?: string | null;
        };
        CreateWebdavAccountReq: {
            password?: string | null;
            /** Format: int64 */
            root_folder_id?: number | null;
            username: string;
        };
        /**
         * @description 存储驱动类型
         * @enum {string}
         */
        DriverType: "local" | "s3";
        /**
         * @description API 错误码，序列化为数字
         * @example 0
         * @enum {integer}
         */
        ErrorCode: 0 | 1000 | 1001 | 1002 | 1003 | 1004 | 1005 | 2000 | 2001 | 2002 | 2003 | 3000 | 3001 | 3002 | 3003 | 3004 | 3005 | 3006 | 3007 | 3008 | 4000 | 4001 | 4002 | 4003 | 5000 | 6000 | 6001 | 6002 | 6003;
        FileInfo: {
            /** Format: int64 */
            blob_id: number;
            created_at: string;
            /** Format: int64 */
            folder_id?: number | null;
            /** Format: int64 */
            id: number;
            mime_type: string;
            name: string;
            updated_at: string;
            /** Format: int64 */
            user_id: number;
        };
        FileQuery: {
            /** Format: int64 */
            folder_id?: number | null;
        };
        FolderContentsResponse: {
            files: components["schemas"]["FileInfo"][];
            folders: components["schemas"]["FolderInfo"][];
        };
        FolderInfo: {
            created_at: string;
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: int64 */
            parent_id?: number | null;
            /** Format: int64 */
            policy_id?: number | null;
            updated_at: string;
            /** Format: int64 */
            user_id: number;
        };
        HealthResponse: {
            build_time: string;
            status: string;
            version: string;
        };
        InitUploadReq: {
            filename: string;
            /** Format: int64 */
            folder_id?: number | null;
            /** Format: int64 */
            total_size: number;
        };
        InitUploadResponse: {
            /** Format: int64 */
            chunk_size?: number | null;
            mode: string;
            /** Format: int32 */
            total_chunks?: number | null;
            upload_id?: string | null;
        };
        LoginReq: {
            password: string;
            username: string;
        };
        PatchFileReq: {
            /** Format: int64 */
            folder_id?: number | null;
            name?: string | null;
        };
        PatchFolderReq: {
            name?: string | null;
            /** Format: int64 */
            parent_id?: number | null;
            /** Format: int64 */
            policy_id?: number | null;
        };
        PatchPolicyReq: {
            access_key?: string | null;
            base_path?: string | null;
            bucket?: string | null;
            /** Format: int64 */
            chunk_size?: number | null;
            endpoint?: string | null;
            is_default?: boolean | null;
            /** Format: int64 */
            max_file_size?: number | null;
            name?: string | null;
            secret_key?: string | null;
        };
        PatchUserPolicyReq: {
            is_default?: boolean | null;
            /** Format: int64 */
            quota_bytes?: number | null;
        };
        PatchUserReq: {
            role?: null | components["schemas"]["UserRole"];
            status?: null | components["schemas"]["UserStatus"];
            /** Format: int64 */
            storage_quota?: number | null;
        };
        RefreshResponse: {
            access_token: string;
        };
        RegisterReq: {
            email: string;
            password: string;
            username: string;
        };
        SetConfigReq: {
            value: string;
        };
        ShareInfo: {
            created_at: string;
            /** Format: int64 */
            download_count: number;
            expires_at?: string | null;
            /** Format: int64 */
            file_id?: number | null;
            /** Format: int64 */
            folder_id?: number | null;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            max_downloads: number;
            token: string;
            updated_at: string;
            /** Format: int64 */
            user_id: number;
            /** Format: int64 */
            view_count: number;
        };
        /** @description 公开返回给前端的分享信息（不含密码哈希和内部 ID） */
        SharePublicInfo: {
            /** Format: int64 */
            download_count: number;
            expires_at?: string | null;
            has_password: boolean;
            is_expired: boolean;
            /** Format: int64 */
            max_downloads: number;
            name: string;
            share_type: string;
            token: string;
            /** Format: int64 */
            view_count: number;
        };
        StoragePolicy: {
            allowed_types: string;
            base_path: string;
            bucket: string;
            /** Format: int64 */
            chunk_size: number;
            created_at: string;
            driver_type: components["schemas"]["DriverType"];
            endpoint: string;
            /** Format: int64 */
            id: number;
            is_default: boolean;
            /** Format: int64 */
            max_file_size: number;
            name: string;
            options: string;
            updated_at: string;
        };
        SystemConfig: {
            /** Format: int64 */
            id: number;
            key: string;
            updated_at: string;
            /** Format: int64 */
            updated_by?: number | null;
            value: string;
        };
        TokenResponse: {
            access_token: string;
            refresh_token: string;
        };
        UploadProgressResponse: {
            chunks_on_disk: number[];
            filename: string;
            /** Format: int32 */
            received_count: number;
            status: string;
            /** Format: int32 */
            total_chunks: number;
            upload_id: string;
        };
        UploadSession: {
            /** Format: int64 */
            chunk_size: number;
            created_at: string;
            expires_at: string;
            filename: string;
            /** Format: int64 */
            folder_id?: number | null;
            id: string;
            /** Format: int64 */
            policy_id: number;
            /** Format: int32 */
            received_count: number;
            status: string;
            /** Format: int32 */
            total_chunks: number;
            /** Format: int64 */
            total_size: number;
            updated_at: string;
            /** Format: int64 */
            user_id: number;
        };
        UserInfo: {
            created_at: string;
            email: string;
            /** Format: int64 */
            id: number;
            role: components["schemas"]["UserRole"];
            status: components["schemas"]["UserStatus"];
            /** Format: int64 */
            storage_quota: number;
            /** Format: int64 */
            storage_used: number;
            updated_at: string;
            username: string;
        };
        /**
         * @description 用户角色
         * @enum {string}
         */
        UserRole: "admin" | "user";
        /**
         * @description 用户状态
         * @enum {string}
         */
        UserStatus: "active" | "disabled";
        UserStoragePolicy: {
            created_at: string;
            /** Format: int64 */
            id: number;
            is_default: boolean;
            /** Format: int64 */
            policy_id: number;
            /** Format: int64 */
            quota_bytes: number;
            /** Format: int64 */
            user_id: number;
        };
        VerifyPasswordReq: {
            password: string;
        };
        WebdavAccount: {
            created_at: string;
            /** Format: int64 */
            id: number;
            is_active: boolean;
            /** Format: int64 */
            root_folder_id?: number | null;
            updated_at: string;
            /** Format: int64 */
            user_id: number;
            username: string;
        };
        /** @description 创建账号后返回的响应（包含一次性明文密码） */
        WebdavAccountCreated: {
            /** Format: int64 */
            id: number;
            /** @description 明文密码，只返回一次 */
            password: string;
            root_folder_path?: string | null;
            username: string;
        };
        /** @description 列表返回用的带路径的账号信息 */
        WebdavAccountInfo: {
            created_at: string;
            /** Format: int64 */
            id: number;
            is_active: boolean;
            /** Format: int64 */
            root_folder_id?: number | null;
            /** @description 文件夹路径，如 "/Documents/Photos"，None 表示全部访问 */
            root_folder_path?: string | null;
            updated_at: string;
            username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all config entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            /** Format: int64 */
                            id: number;
                            key: string;
                            updated_at: string;
                            /** Format: int64 */
                            updated_by?: number | null;
                            value: string;
                        }[];
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Config key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Config entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            /** Format: int64 */
                            id: number;
                            key: string;
                            updated_at: string;
                            /** Format: int64 */
                            updated_by?: number | null;
                            value: string;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Config key not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    set_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Config key */
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetConfigReq"];
            };
        };
        responses: {
            /** @description Config value set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            /** Format: int64 */
                            id: number;
                            key: string;
                            updated_at: string;
                            /** Format: int64 */
                            updated_by?: number | null;
                            value: string;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Config key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Config entry deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Config key not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_policies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all storage policies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            allowed_types: string;
                            base_path: string;
                            bucket: string;
                            /** Format: int64 */
                            chunk_size: number;
                            created_at: string;
                            driver_type: components["schemas"]["DriverType"];
                            endpoint: string;
                            /** Format: int64 */
                            id: number;
                            is_default: boolean;
                            /** Format: int64 */
                            max_file_size: number;
                            name: string;
                            options: string;
                            updated_at: string;
                        }[];
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_policy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePolicyReq"];
            };
        };
        responses: {
            /** @description Policy created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            allowed_types: string;
                            base_path: string;
                            bucket: string;
                            /** Format: int64 */
                            chunk_size: number;
                            created_at: string;
                            driver_type: components["schemas"]["DriverType"];
                            endpoint: string;
                            /** Format: int64 */
                            id: number;
                            is_default: boolean;
                            /** Format: int64 */
                            max_file_size: number;
                            name: string;
                            options: string;
                            updated_at: string;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Policy ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policy details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            allowed_types: string;
                            base_path: string;
                            bucket: string;
                            /** Format: int64 */
                            chunk_size: number;
                            created_at: string;
                            driver_type: components["schemas"]["DriverType"];
                            endpoint: string;
                            /** Format: int64 */
                            id: number;
                            is_default: boolean;
                            /** Format: int64 */
                            max_file_size: number;
                            name: string;
                            options: string;
                            updated_at: string;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Policy not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Policy ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policy deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Policy not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Policy ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchPolicyReq"];
            };
        };
        responses: {
            /** @description Policy updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            allowed_types: string;
                            base_path: string;
                            bucket: string;
                            /** Format: int64 */
                            chunk_size: number;
                            created_at: string;
                            driver_type: components["schemas"]["DriverType"];
                            endpoint: string;
                            /** Format: int64 */
                            id: number;
                            is_default: boolean;
                            /** Format: int64 */
                            max_file_size: number;
                            name: string;
                            options: string;
                            updated_at: string;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Policy not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_all_shares: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All shares */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            created_at: string;
                            /** Format: int64 */
                            download_count: number;
                            expires_at?: string | null;
                            /** Format: int64 */
                            file_id?: number | null;
                            /** Format: int64 */
                            folder_id?: number | null;
                            /** Format: int64 */
                            id: number;
                            /** Format: int64 */
                            max_downloads: number;
                            token: string;
                            updated_at: string;
                            /** Format: int64 */
                            user_id: number;
                            /** Format: int64 */
                            view_count: number;
                        }[];
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_delete_share: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Share deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Share not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            created_at: string;
                            email: string;
                            /** Format: int64 */
                            id: number;
                            role: components["schemas"]["UserRole"];
                            status: components["schemas"]["UserStatus"];
                            /** Format: int64 */
                            storage_quota: number;
                            /** Format: int64 */
                            storage_used: number;
                            updated_at: string;
                            username: string;
                        }[];
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            created_at: string;
                            email: string;
                            /** Format: int64 */
                            id: number;
                            role: components["schemas"]["UserRole"];
                            status: components["schemas"]["UserStatus"];
                            /** Format: int64 */
                            storage_quota: number;
                            /** Format: int64 */
                            storage_used: number;
                            updated_at: string;
                            username: string;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchUserReq"];
            };
        };
        responses: {
            /** @description User updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            created_at: string;
                            email: string;
                            /** Format: int64 */
                            id: number;
                            role: components["schemas"]["UserRole"];
                            status: components["schemas"]["UserStatus"];
                            /** Format: int64 */
                            storage_quota: number;
                            /** Format: int64 */
                            storage_used: number;
                            updated_at: string;
                            username: string;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_user_policies: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User policy assignments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            created_at: string;
                            /** Format: int64 */
                            id: number;
                            is_default: boolean;
                            /** Format: int64 */
                            policy_id: number;
                            /** Format: int64 */
                            quota_bytes: number;
                            /** Format: int64 */
                            user_id: number;
                        }[];
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    assign_user_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignUserPolicyReq"];
            };
        };
        responses: {
            /** @description Policy assigned */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            created_at: string;
                            /** Format: int64 */
                            id: number;
                            is_default: boolean;
                            /** Format: int64 */
                            policy_id: number;
                            /** Format: int64 */
                            quota_bytes: number;
                            /** Format: int64 */
                            user_id: number;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Policy not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remove_user_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                user_id: number;
                /** @description User storage policy assignment ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assignment removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Assignment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_user_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                user_id: number;
                /** @description User storage policy assignment ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchUserPolicyReq"];
            };
        };
        responses: {
            /** @description Assignment updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            created_at: string;
                            /** Format: int64 */
                            id: number;
                            is_default: boolean;
                            /** Format: int64 */
                            policy_id: number;
                            /** Format: int64 */
                            quota_bytes: number;
                            /** Format: int64 */
                            user_id: number;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Assignment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginReq"];
            };
        };
        responses: {
            /** @description Login successful, tokens set in HttpOnly cookies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out, cookies cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            created_at: string;
                            email: string;
                            /** Format: int64 */
                            id: number;
                            role: components["schemas"]["UserRole"];
                            status: components["schemas"]["UserStatus"];
                            /** Format: int64 */
                            storage_quota: number;
                            /** Format: int64 */
                            storage_used: number;
                            updated_at: string;
                            username: string;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token refreshed, new access token set in HttpOnly cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterReq"];
            };
        };
        responses: {
            /** @description Registration successful */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            created_at: string;
                            email: string;
                            /** Format: int64 */
                            id: number;
                            role: components["schemas"]["UserRole"];
                            status: components["schemas"]["UserStatus"];
                            /** Format: int64 */
                            storage_quota: number;
                            /** Format: int64 */
                            storage_used: number;
                            updated_at: string;
                            username: string;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upload_file: {
        parameters: {
            query?: {
                folder_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description File to upload */
        requestBody: {
            content: {
                "multipart/form-data": string;
            };
        };
        responses: {
            /** @description File uploaded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            /** Format: int64 */
                            blob_id: number;
                            created_at: string;
                            /** Format: int64 */
                            folder_id?: number | null;
                            /** Format: int64 */
                            id: number;
                            mime_type: string;
                            name: string;
                            updated_at: string;
                            /** Format: int64 */
                            user_id: number;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    init_chunked_upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitUploadReq"];
            };
        };
        responses: {
            /** @description Upload session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            /** Format: int64 */
                            chunk_size?: number | null;
                            mode: string;
                            /** Format: int32 */
                            total_chunks?: number | null;
                            upload_id?: string | null;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_upload_progress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Upload session ID */
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload progress */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            chunks_on_disk: number[];
                            filename: string;
                            /** Format: int32 */
                            received_count: number;
                            status: string;
                            /** Format: int32 */
                            total_chunks: number;
                            upload_id: string;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancel_upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Upload session ID */
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    complete_chunked_upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Upload session ID */
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            /** Format: int64 */
                            blob_id: number;
                            created_at: string;
                            /** Format: int64 */
                            folder_id?: number | null;
                            /** Format: int64 */
                            id: number;
                            mime_type: string;
                            name: string;
                            updated_at: string;
                            /** Format: int64 */
                            user_id: number;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upload_chunk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Upload session ID */
                upload_id: string;
                /** @description Chunk number (0-indexed) */
                chunk_number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": number[];
            };
        };
        responses: {
            /** @description Chunk uploaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            /** Format: int32 */
                            received_count: number;
                            /** Format: int32 */
                            total_chunks: number;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description File ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            /** Format: int64 */
                            blob_id: number;
                            created_at: string;
                            /** Format: int64 */
                            folder_id?: number | null;
                            /** Format: int64 */
                            id: number;
                            mime_type: string;
                            name: string;
                            updated_at: string;
                            /** Format: int64 */
                            user_id: number;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description File not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description File ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description File not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch_file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description File ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchFileReq"];
            };
        };
        responses: {
            /** @description File updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            /** Format: int64 */
                            blob_id: number;
                            created_at: string;
                            /** Format: int64 */
                            folder_id?: number | null;
                            /** Format: int64 */
                            id: number;
                            mime_type: string;
                            name: string;
                            updated_at: string;
                            /** Format: int64 */
                            user_id: number;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description File not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    download_file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description File ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description File not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_thumbnail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description File ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thumbnail image (WebP) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found or not an image */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_root: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Root folder contents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            files: components["schemas"]["FileInfo"][];
                            folders: components["schemas"]["FolderInfo"][];
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_folder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFolderReq"];
            };
        };
        responses: {
            /** @description Folder created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            created_at: string;
                            /** Format: int64 */
                            id: number;
                            name: string;
                            /** Format: int64 */
                            parent_id?: number | null;
                            /** Format: int64 */
                            policy_id?: number | null;
                            updated_at: string;
                            /** Format: int64 */
                            user_id: number;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_folder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Folder ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Folder contents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            files: components["schemas"]["FileInfo"][];
                            folders: components["schemas"]["FolderInfo"][];
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Folder not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_folder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Folder ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Folder deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Folder not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch_folder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Folder ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchFolderReq"];
            };
        };
        responses: {
            /** @description Folder updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            created_at: string;
                            /** Format: int64 */
                            id: number;
                            name: string;
                            /** Format: int64 */
                            parent_id?: number | null;
                            /** Format: int64 */
                            policy_id?: number | null;
                            updated_at: string;
                            /** Format: int64 */
                            user_id: number;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Folder not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_share_info: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share token */
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Share info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        /** @description 公开返回给前端的分享信息（不含密码哈希和内部 ID） */
                        data?: {
                            /** Format: int64 */
                            download_count: number;
                            expires_at?: string | null;
                            has_password: boolean;
                            is_expired: boolean;
                            /** Format: int64 */
                            max_downloads: number;
                            name: string;
                            share_type: string;
                            token: string;
                            /** Format: int64 */
                            view_count: number;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Share not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Share expired */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_shared_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share token */
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Folder contents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            files: components["schemas"]["FileInfo"][];
                            folders: components["schemas"]["FolderInfo"][];
                        };
                        msg: string;
                    };
                };
            };
            /** @description Password required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Share not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    download_shared_file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share token */
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Password required or download limit */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Share not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verify_share_password: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share token */
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyPasswordReq"];
            };
        };
        responses: {
            /** @description Password verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wrong password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Share not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_my_shares: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description My shares */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            created_at: string;
                            /** Format: int64 */
                            download_count: number;
                            expires_at?: string | null;
                            /** Format: int64 */
                            file_id?: number | null;
                            /** Format: int64 */
                            folder_id?: number | null;
                            /** Format: int64 */
                            id: number;
                            /** Format: int64 */
                            max_downloads: number;
                            token: string;
                            updated_at: string;
                            /** Format: int64 */
                            user_id: number;
                            /** Format: int64 */
                            view_count: number;
                        }[];
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_share: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShareReq"];
            };
        };
        responses: {
            /** @description Share created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            created_at: string;
                            /** Format: int64 */
                            download_count: number;
                            expires_at?: string | null;
                            /** Format: int64 */
                            file_id?: number | null;
                            /** Format: int64 */
                            folder_id?: number | null;
                            /** Format: int64 */
                            id: number;
                            /** Format: int64 */
                            max_downloads: number;
                            token: string;
                            updated_at: string;
                            /** Format: int64 */
                            user_id: number;
                            /** Format: int64 */
                            view_count: number;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_share: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Share deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Share not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_webdav_accounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebDAV accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            created_at: string;
                            /** Format: int64 */
                            id: number;
                            is_active: boolean;
                            /** Format: int64 */
                            root_folder_id?: number | null;
                            /** @description 文件夹路径，如 "/Documents/Photos"，None 表示全部访问 */
                            root_folder_path?: string | null;
                            updated_at: string;
                            username: string;
                        }[];
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_webdav_account: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWebdavAccountReq"];
            };
        };
        responses: {
            /** @description Account created (password shown once) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        /** @description 创建账号后返回的响应（包含一次性明文密码） */
                        data?: {
                            /** Format: int64 */
                            id: number;
                            /** @description 明文密码，只返回一次 */
                            password: string;
                            root_folder_path?: string | null;
                            username: string;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_webdav_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    toggle_webdav_account: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account toggled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            created_at: string;
                            /** Format: int64 */
                            id: number;
                            is_active: boolean;
                            /** Format: int64 */
                            root_folder_id?: number | null;
                            updated_at: string;
                            /** Format: int64 */
                            user_id: number;
                            username: string;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            build_time: string;
                            status: string;
                            version: string;
                        };
                        msg: string;
                    };
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: components["schemas"]["ErrorCode"];
                        data?: {
                            build_time: string;
                            status: string;
                            version: string;
                        };
                        msg: string;
                    };
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
