/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/v1/admin/config": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_config"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/admin/config/{key}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_config"];
		put: operations["set_config"];
		post?: never;
		delete: operations["delete_config"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/admin/policies": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_policies"];
		put?: never;
		post: operations["create_policy"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/admin/policies/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_policy"];
		put?: never;
		post?: never;
		delete: operations["delete_policy"];
		options?: never;
		head?: never;
		patch: operations["update_policy"];
		trace?: never;
	};
	"/api/v1/admin/users": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_users"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/admin/users/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_user"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch: operations["update_user"];
		trace?: never;
	};
	"/api/v1/auth/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["login"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["logout"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["me"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/refresh": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["refresh"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/register": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["register"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/files/upload": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["upload_file"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/files/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_file"];
		put?: never;
		post?: never;
		delete: operations["delete_file"];
		options?: never;
		head?: never;
		patch: operations["patch_file"];
		trace?: never;
	};
	"/api/v1/files/{id}/download": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["download_file"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/folders": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_root"];
		put?: never;
		post: operations["create_folder"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/folders/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_folder"];
		put?: never;
		post?: never;
		delete: operations["delete_folder"];
		options?: never;
		head?: never;
		patch: operations["patch_folder"];
		trace?: never;
	};
	"/health": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["health"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/health/ready": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["ready"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		CreateFolderReq: {
			name: string;
			/** Format: int64 */
			parent_id?: number | null;
		};
		CreatePolicyReq: {
			access_key?: string | null;
			base_path?: string | null;
			bucket?: string | null;
			driver_type: components["schemas"]["DriverType"];
			endpoint?: string | null;
			is_default?: boolean | null;
			/** Format: int64 */
			max_file_size?: number | null;
			name: string;
			secret_key?: string | null;
		};
		/**
		 * @description 存储驱动类型
		 * @enum {string}
		 */
		DriverType: "local" | "s3";
		/**
		 * @description API 错误码，序列化为数字
		 * @example 0
		 * @enum {integer}
		 */
		ErrorCode:
			| 0
			| 1000
			| 1001
			| 1002
			| 1003
			| 1004
			| 1005
			| 2000
			| 2001
			| 2002
			| 2003
			| 3000
			| 3001
			| 3002
			| 3003
			| 4000
			| 4001
			| 4002
			| 4003
			| 5000;
		FileInfo: {
			/** Format: int64 */
			blob_id: number;
			created_at: string;
			/** Format: int64 */
			folder_id?: number | null;
			/** Format: int64 */
			id: number;
			mime_type: string;
			name: string;
			updated_at: string;
			/** Format: int64 */
			user_id: number;
		};
		FileQuery: {
			/** Format: int64 */
			folder_id?: number | null;
		};
		FolderContentsResponse: {
			files: components["schemas"]["FileInfo"][];
			folders: components["schemas"]["FolderInfo"][];
		};
		FolderInfo: {
			created_at: string;
			/** Format: int64 */
			id: number;
			name: string;
			/** Format: int64 */
			parent_id?: number | null;
			/** Format: int64 */
			policy_id?: number | null;
			updated_at: string;
			/** Format: int64 */
			user_id: number;
		};
		HealthResponse: {
			build_time: string;
			status: string;
			version: string;
		};
		LoginReq: {
			password: string;
			username: string;
		};
		PatchFileReq: {
			/** Format: int64 */
			folder_id?: number | null;
			name?: string | null;
		};
		PatchFolderReq: {
			name?: string | null;
			/** Format: int64 */
			parent_id?: number | null;
			/** Format: int64 */
			policy_id?: number | null;
		};
		PatchPolicyReq: {
			access_key?: string | null;
			base_path?: string | null;
			bucket?: string | null;
			endpoint?: string | null;
			is_default?: boolean | null;
			/** Format: int64 */
			max_file_size?: number | null;
			name?: string | null;
			secret_key?: string | null;
		};
		PatchUserReq: {
			role?: null | components["schemas"]["UserRole"];
			status?: null | components["schemas"]["UserStatus"];
		};
		RefreshResponse: {
			access_token: string;
		};
		RegisterReq: {
			email: string;
			password: string;
			username: string;
		};
		SetConfigReq: {
			value: string;
		};
		StoragePolicy: {
			allowed_types: string;
			base_path: string;
			bucket: string;
			created_at: string;
			driver_type: components["schemas"]["DriverType"];
			endpoint: string;
			/** Format: int64 */
			id: number;
			is_default: boolean;
			/** Format: int64 */
			max_file_size: number;
			name: string;
			options: string;
			updated_at: string;
		};
		SystemConfig: {
			/** Format: int64 */
			id: number;
			key: string;
			updated_at: string;
			/** Format: int64 */
			updated_by?: number | null;
			value: string;
		};
		TokenResponse: {
			access_token: string;
			refresh_token: string;
		};
		UserInfo: {
			created_at: string;
			email: string;
			/** Format: int64 */
			id: number;
			role: components["schemas"]["UserRole"];
			status: components["schemas"]["UserStatus"];
			/** Format: int64 */
			storage_used: number;
			updated_at: string;
			username: string;
		};
		/**
		 * @description 用户角色
		 * @enum {string}
		 */
		UserRole: "admin" | "user";
		/**
		 * @description 用户状态
		 * @enum {string}
		 */
		UserStatus: "active" | "disabled";
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	list_config: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List all config entries */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						code: components["schemas"]["ErrorCode"];
						data?: {
							/** Format: int64 */
							id: number;
							key: string;
							updated_at: string;
							/** Format: int64 */
							updated_by?: number | null;
							value: string;
						}[];
						msg: string;
					};
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_config: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Config key */
				key: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Config entry */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						code: components["schemas"]["ErrorCode"];
						data?: {
							/** Format: int64 */
							id: number;
							key: string;
							updated_at: string;
							/** Format: int64 */
							updated_by?: number | null;
							value: string;
						};
						msg: string;
					};
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Config key not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	set_config: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Config key */
				key: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SetConfigReq"];
			};
		};
		responses: {
			/** @description Config value set */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						code: components["schemas"]["ErrorCode"];
						data?: {
							/** Format: int64 */
							id: number;
							key: string;
							updated_at: string;
							/** Format: int64 */
							updated_by?: number | null;
							value: string;
						};
						msg: string;
					};
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	delete_config: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Config key */
				key: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Config entry deleted */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Config key not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	list_policies: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List all storage policies */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						code: components["schemas"]["ErrorCode"];
						data?: {
							allowed_types: string;
							base_path: string;
							bucket: string;
							created_at: string;
							driver_type: components["schemas"]["DriverType"];
							endpoint: string;
							/** Format: int64 */
							id: number;
							is_default: boolean;
							/** Format: int64 */
							max_file_size: number;
							name: string;
							options: string;
							updated_at: string;
						}[];
						msg: string;
					};
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	create_policy: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreatePolicyReq"];
			};
		};
		responses: {
			/** @description Policy created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						code: components["schemas"]["ErrorCode"];
						data?: {
							allowed_types: string;
							base_path: string;
							bucket: string;
							created_at: string;
							driver_type: components["schemas"]["DriverType"];
							endpoint: string;
							/** Format: int64 */
							id: number;
							is_default: boolean;
							/** Format: int64 */
							max_file_size: number;
							name: string;
							options: string;
							updated_at: string;
						};
						msg: string;
					};
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_policy: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Policy ID */
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Policy details */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						code: components["schemas"]["ErrorCode"];
						data?: {
							allowed_types: string;
							base_path: string;
							bucket: string;
							created_at: string;
							driver_type: components["schemas"]["DriverType"];
							endpoint: string;
							/** Format: int64 */
							id: number;
							is_default: boolean;
							/** Format: int64 */
							max_file_size: number;
							name: string;
							options: string;
							updated_at: string;
						};
						msg: string;
					};
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Policy not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	delete_policy: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Policy ID */
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Policy deleted */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Policy not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	update_policy: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Policy ID */
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["PatchPolicyReq"];
			};
		};
		responses: {
			/** @description Policy updated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						code: components["schemas"]["ErrorCode"];
						data?: {
							allowed_types: string;
							base_path: string;
							bucket: string;
							created_at: string;
							driver_type: components["schemas"]["DriverType"];
							endpoint: string;
							/** Format: int64 */
							id: number;
							is_default: boolean;
							/** Format: int64 */
							max_file_size: number;
							name: string;
							options: string;
							updated_at: string;
						};
						msg: string;
					};
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Policy not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	list_users: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List all users */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						code: components["schemas"]["ErrorCode"];
						data?: {
							created_at: string;
							email: string;
							/** Format: int64 */
							id: number;
							role: components["schemas"]["UserRole"];
							status: components["schemas"]["UserStatus"];
							/** Format: int64 */
							storage_used: number;
							updated_at: string;
							username: string;
						}[];
						msg: string;
					};
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_user: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description User ID */
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description User details */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						code: components["schemas"]["ErrorCode"];
						data?: {
							created_at: string;
							email: string;
							/** Format: int64 */
							id: number;
							role: components["schemas"]["UserRole"];
							status: components["schemas"]["UserStatus"];
							/** Format: int64 */
							storage_used: number;
							updated_at: string;
							username: string;
						};
						msg: string;
					};
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description User not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	update_user: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description User ID */
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["PatchUserReq"];
			};
		};
		responses: {
			/** @description User updated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						code: components["schemas"]["ErrorCode"];
						data?: {
							created_at: string;
							email: string;
							/** Format: int64 */
							id: number;
							role: components["schemas"]["UserRole"];
							status: components["schemas"]["UserStatus"];
							/** Format: int64 */
							storage_used: number;
							updated_at: string;
							username: string;
						};
						msg: string;
					};
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description User not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	login: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["LoginReq"];
			};
		};
		responses: {
			/** @description Login successful, tokens set in HttpOnly cookies */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid credentials */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	logout: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Logged out, cookies cleared */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	me: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Current user info */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						code: components["schemas"]["ErrorCode"];
						data?: {
							created_at: string;
							email: string;
							/** Format: int64 */
							id: number;
							role: components["schemas"]["UserRole"];
							status: components["schemas"]["UserStatus"];
							/** Format: int64 */
							storage_used: number;
							updated_at: string;
							username: string;
						};
						msg: string;
					};
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	refresh: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Token refreshed, new access token set in HttpOnly cookie */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid refresh token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	register: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["RegisterReq"];
			};
		};
		responses: {
			/** @description Registration successful */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						code: components["schemas"]["ErrorCode"];
						data?: {
							created_at: string;
							email: string;
							/** Format: int64 */
							id: number;
							role: components["schemas"]["UserRole"];
							status: components["schemas"]["UserStatus"];
							/** Format: int64 */
							storage_used: number;
							updated_at: string;
							username: string;
						};
						msg: string;
					};
				};
			};
			/** @description Validation error */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	upload_file: {
		parameters: {
			query?: {
				folder_id?: number | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description File to upload */
		requestBody: {
			content: {
				"multipart/form-data": string;
			};
		};
		responses: {
			/** @description File uploaded */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						code: components["schemas"]["ErrorCode"];
						data?: {
							/** Format: int64 */
							blob_id: number;
							created_at: string;
							/** Format: int64 */
							folder_id?: number | null;
							/** Format: int64 */
							id: number;
							mime_type: string;
							name: string;
							updated_at: string;
							/** Format: int64 */
							user_id: number;
						};
						msg: string;
					};
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_file: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description File ID */
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description File info */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						code: components["schemas"]["ErrorCode"];
						data?: {
							/** Format: int64 */
							blob_id: number;
							created_at: string;
							/** Format: int64 */
							folder_id?: number | null;
							/** Format: int64 */
							id: number;
							mime_type: string;
							name: string;
							updated_at: string;
							/** Format: int64 */
							user_id: number;
						};
						msg: string;
					};
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description File not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	delete_file: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description File ID */
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description File deleted */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description File not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	patch_file: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description File ID */
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["PatchFileReq"];
			};
		};
		responses: {
			/** @description File updated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						code: components["schemas"]["ErrorCode"];
						data?: {
							/** Format: int64 */
							blob_id: number;
							created_at: string;
							/** Format: int64 */
							folder_id?: number | null;
							/** Format: int64 */
							id: number;
							mime_type: string;
							name: string;
							updated_at: string;
							/** Format: int64 */
							user_id: number;
						};
						msg: string;
					};
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description File not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	download_file: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description File ID */
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description File content */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description File not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	list_root: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Root folder contents */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						code: components["schemas"]["ErrorCode"];
						data?: {
							files: components["schemas"]["FileInfo"][];
							folders: components["schemas"]["FolderInfo"][];
						};
						msg: string;
					};
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	create_folder: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateFolderReq"];
			};
		};
		responses: {
			/** @description Folder created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						code: components["schemas"]["ErrorCode"];
						data?: {
							created_at: string;
							/** Format: int64 */
							id: number;
							name: string;
							/** Format: int64 */
							parent_id?: number | null;
							/** Format: int64 */
							policy_id?: number | null;
							updated_at: string;
							/** Format: int64 */
							user_id: number;
						};
						msg: string;
					};
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	list_folder: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Folder ID */
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Folder contents */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						code: components["schemas"]["ErrorCode"];
						data?: {
							files: components["schemas"]["FileInfo"][];
							folders: components["schemas"]["FolderInfo"][];
						};
						msg: string;
					};
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Folder not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	delete_folder: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Folder ID */
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Folder deleted */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Folder not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	patch_folder: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Folder ID */
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["PatchFolderReq"];
			};
		};
		responses: {
			/** @description Folder updated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						code: components["schemas"]["ErrorCode"];
						data?: {
							created_at: string;
							/** Format: int64 */
							id: number;
							name: string;
							/** Format: int64 */
							parent_id?: number | null;
							/** Format: int64 */
							policy_id?: number | null;
							updated_at: string;
							/** Format: int64 */
							user_id: number;
						};
						msg: string;
					};
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Folder not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	health: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Service is healthy */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						code: components["schemas"]["ErrorCode"];
						data?: {
							build_time: string;
							status: string;
							version: string;
						};
						msg: string;
					};
				};
			};
		};
	};
	ready: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Service is ready */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						code: components["schemas"]["ErrorCode"];
						data?: {
							build_time: string;
							status: string;
							version: string;
						};
						msg: string;
					};
				};
			};
			/** @description Service unavailable */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
}
