//! 运行时配置定义 — 所有 system_config 键的单一数据源
//!
//! 启动时 `ensure_defaults()` 遍历此数组，
//! 对每项执行 INSERT ... ON CONFLICT DO NOTHING。

/// 单条配置定义
pub struct ConfigDef {
    /// 配置键（数据库 unique key）
    pub key: &'static str,
    /// 前端显示名称的 i18n key
    pub label_i18n_key: &'static str,
    /// 前端描述文案的 i18n key
    pub description_i18n_key: &'static str,
    /// 值类型：前端渲染用
    pub value_type: &'static str,
    /// 默认值生成函数
    pub default_fn: fn() -> String,
    /// 修改后是否需要重启
    pub requires_restart: bool,
    /// 是否敏感值
    pub is_sensitive: bool,
    /// 分类（前端分组用）
    pub category: &'static str,
    /// 描述
    pub description: &'static str,
}

/// 所有运行时配置项
pub static ALL_CONFIGS: &[ConfigDef] = &[
    // ── Auth ────────────────────────────────────────────────
    ConfigDef {
        key: "auth_cookie_secure",
        label_i18n_key: "settings_item_auth_cookie_secure_label",
        description_i18n_key: "settings_item_auth_cookie_secure_desc",
        value_type: "boolean",
        default_fn: || "true".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "auth",
        description: "Whether auth and share verification cookies require HTTPS",
    },
    ConfigDef {
        key: "auth_access_token_ttl_secs",
        label_i18n_key: "settings_item_auth_access_token_ttl_secs_label",
        description_i18n_key: "settings_item_auth_access_token_ttl_secs_desc",
        value_type: "number",
        default_fn: || "900".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "auth",
        description: "Access token lifetime in seconds",
    },
    ConfigDef {
        key: "auth_refresh_token_ttl_secs",
        label_i18n_key: "settings_item_auth_refresh_token_ttl_secs_label",
        description_i18n_key: "settings_item_auth_refresh_token_ttl_secs_desc",
        value_type: "number",
        default_fn: || "604800".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "auth",
        description: "Refresh token lifetime in seconds",
    },
    ConfigDef {
        key: "auth_register_activation_ttl_secs",
        label_i18n_key: "settings_item_auth_register_activation_ttl_secs_label",
        description_i18n_key: "settings_item_auth_register_activation_ttl_secs_desc",
        value_type: "number",
        default_fn: || "86400".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "auth",
        description: "Registration activation link lifetime in seconds",
    },
    ConfigDef {
        key: "auth_contact_change_ttl_secs",
        label_i18n_key: "settings_item_auth_contact_change_ttl_secs_label",
        description_i18n_key: "settings_item_auth_contact_change_ttl_secs_desc",
        value_type: "number",
        default_fn: || "86400".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "auth",
        description: "Contact change confirmation link lifetime in seconds",
    },
    ConfigDef {
        key: "auth_password_reset_ttl_secs",
        label_i18n_key: "settings_item_auth_password_reset_ttl_secs_label",
        description_i18n_key: "settings_item_auth_password_reset_ttl_secs_desc",
        value_type: "number",
        default_fn: || "3600".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "auth",
        description: "Password reset link lifetime in seconds",
    },
    ConfigDef {
        key: "auth_contact_verification_resend_cooldown_secs",
        label_i18n_key: "settings_item_auth_contact_verification_resend_cooldown_secs_label",
        description_i18n_key: "settings_item_auth_contact_verification_resend_cooldown_secs_desc",
        value_type: "number",
        default_fn: || "60".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "auth",
        description: "Minimum cooldown between verification email resends in seconds",
    },
    ConfigDef {
        key: "auth_password_reset_request_cooldown_secs",
        label_i18n_key: "settings_item_auth_password_reset_request_cooldown_secs_label",
        description_i18n_key: "settings_item_auth_password_reset_request_cooldown_secs_desc",
        value_type: "number",
        default_fn: || "60".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "auth",
        description: "Minimum cooldown between password reset email requests for the same user in seconds",
    },
    // ── WebDAV ──────────────────────────────────────────────
    ConfigDef {
        key: "webdav_enabled",
        label_i18n_key: "settings_item_webdav_enabled_label",
        description_i18n_key: "settings_item_webdav_enabled_desc",
        value_type: "boolean",
        default_fn: || "true".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "webdav",
        description: "Enable or disable WebDAV access",
    },
    // ── Network ─────────────────────────────────────────────
    ConfigDef {
        key: "cors_enabled",
        label_i18n_key: "settings_item_cors_enabled_label",
        description_i18n_key: "settings_item_cors_enabled_desc",
        value_type: "boolean",
        default_fn: || "false".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "network",
        description: "Enable CORS handling for cross-origin browser requests. When disabled, the server skips all CORS headers and enforcement",
    },
    ConfigDef {
        key: "cors_allowed_origins",
        label_i18n_key: "settings_item_cors_allowed_origins_label",
        description_i18n_key: "settings_item_cors_allowed_origins_desc",
        value_type: "string",
        default_fn: || String::new(),
        requires_restart: false,
        is_sensitive: false,
        category: "network",
        description: "Comma-separated CORS origin whitelist. Empty = skip CORS headers and let the browser block cross-origin access, '*' = allow any origin",
    },
    ConfigDef {
        key: "cors_allow_credentials",
        label_i18n_key: "settings_item_cors_allow_credentials_label",
        description_i18n_key: "settings_item_cors_allow_credentials_desc",
        value_type: "boolean",
        default_fn: || "false".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "network",
        description: "Whether CORS responses include Access-Control-Allow-Credentials",
    },
    ConfigDef {
        key: "cors_max_age_secs",
        label_i18n_key: "settings_item_cors_max_age_secs_label",
        description_i18n_key: "settings_item_cors_max_age_secs_desc",
        value_type: "number",
        default_fn: || "3600".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "network",
        description: "CORS preflight cache duration in seconds",
    },
    // ── Operations ──────────────────────────────────────────
    ConfigDef {
        key: "mail_outbox_dispatch_interval_secs",
        label_i18n_key: "settings_item_mail_outbox_dispatch_interval_secs_label",
        description_i18n_key: "settings_item_mail_outbox_dispatch_interval_secs_desc",
        value_type: "number",
        default_fn: || {
            crate::config::operations::DEFAULT_MAIL_OUTBOX_DISPATCH_INTERVAL_SECS.to_string()
        },
        requires_restart: false,
        is_sensitive: false,
        category: "operations",
        description: "Seconds between mail outbox dispatch polls",
    },
    ConfigDef {
        key: "background_task_dispatch_interval_secs",
        label_i18n_key: "settings_item_background_task_dispatch_interval_secs_label",
        description_i18n_key: "settings_item_background_task_dispatch_interval_secs_desc",
        value_type: "number",
        default_fn: || {
            crate::config::operations::DEFAULT_BACKGROUND_TASK_DISPATCH_INTERVAL_SECS.to_string()
        },
        requires_restart: false,
        is_sensitive: false,
        category: "operations",
        description: "Seconds between background task dispatch polls",
    },
    ConfigDef {
        key: "maintenance_cleanup_interval_secs",
        label_i18n_key: "settings_item_maintenance_cleanup_interval_secs_label",
        description_i18n_key: "settings_item_maintenance_cleanup_interval_secs_desc",
        value_type: "number",
        default_fn: || {
            crate::config::operations::DEFAULT_MAINTENANCE_CLEANUP_INTERVAL_SECS.to_string()
        },
        requires_restart: false,
        is_sensitive: false,
        category: "operations",
        description: "Seconds between periodic maintenance cleanup runs",
    },
    ConfigDef {
        key: "blob_reconcile_interval_secs",
        label_i18n_key: "settings_item_blob_reconcile_interval_secs_label",
        description_i18n_key: "settings_item_blob_reconcile_interval_secs_desc",
        value_type: "number",
        default_fn: || crate::config::operations::DEFAULT_BLOB_RECONCILE_INTERVAL_SECS.to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "operations",
        description: "Seconds between full blob reconciliation runs",
    },
    ConfigDef {
        key: "team_member_list_max_limit",
        label_i18n_key: "settings_item_team_member_list_max_limit_label",
        description_i18n_key: "settings_item_team_member_list_max_limit_desc",
        value_type: "number",
        default_fn: || crate::config::operations::DEFAULT_TEAM_MEMBER_LIST_MAX_LIMIT.to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "operations",
        description: "Maximum page size accepted by team member listing endpoints",
    },
    ConfigDef {
        key: "task_list_max_limit",
        label_i18n_key: "settings_item_task_list_max_limit_label",
        description_i18n_key: "settings_item_task_list_max_limit_desc",
        value_type: "number",
        default_fn: || crate::config::operations::DEFAULT_TASK_LIST_MAX_LIMIT.to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "operations",
        description: "Maximum page size accepted by background task listing endpoints",
    },
    // ── Storage ─────────────────────────────────────────────
    ConfigDef {
        key: "max_versions_per_file",
        label_i18n_key: "settings_item_max_versions_per_file_label",
        description_i18n_key: "settings_item_max_versions_per_file_desc",
        value_type: "number",
        default_fn: || "10".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "storage",
        description: "Maximum number of historical versions kept per file",
    },
    ConfigDef {
        key: "trash_retention_days",
        label_i18n_key: "settings_item_trash_retention_days_label",
        description_i18n_key: "settings_item_trash_retention_days_desc",
        value_type: "number",
        default_fn: || "7".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "storage",
        description: "Days before soft-deleted items are permanently purged",
    },
    ConfigDef {
        key: "team_archive_retention_days",
        label_i18n_key: "settings_item_team_archive_retention_days_label",
        description_i18n_key: "settings_item_team_archive_retention_days_desc",
        value_type: "number",
        default_fn: || "7".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "storage",
        description: "Days before archived teams are permanently deleted",
    },
    ConfigDef {
        key: "task_retention_hours",
        label_i18n_key: "settings_item_task_retention_hours_label",
        description_i18n_key: "settings_item_task_retention_hours_desc",
        value_type: "number",
        default_fn: || "24".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "storage",
        description: "Hours before completed background tasks and task artifacts are permanently deleted",
    },
    ConfigDef {
        key: "default_storage_quota",
        label_i18n_key: "settings_item_default_storage_quota_label",
        description_i18n_key: "settings_item_default_storage_quota_desc",
        value_type: "number",
        default_fn: || "0".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "storage",
        description: "Default storage quota for new users in bytes (0 = unlimited)",
    },
    ConfigDef {
        key: "thumbnail_max_source_bytes",
        label_i18n_key: "settings_item_thumbnail_max_source_bytes_label",
        description_i18n_key: "settings_item_thumbnail_max_source_bytes_desc",
        value_type: "number",
        default_fn: || crate::config::operations::DEFAULT_THUMBNAIL_MAX_SOURCE_BYTES.to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "storage",
        description: "Maximum original file size eligible for thumbnail generation in bytes",
    },
    // ── User ───────────────────────────────────────────────
    ConfigDef {
        key: "auth_allow_user_registration",
        label_i18n_key: "settings_item_auth_allow_user_registration_label",
        description_i18n_key: "settings_item_auth_allow_user_registration_desc",
        value_type: "boolean",
        default_fn: || "true".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "user.registration_and_login",
        description: "Whether new users can self-register from the public auth flow",
    },
    ConfigDef {
        key: "auth_register_activation_enabled",
        label_i18n_key: "settings_item_auth_register_activation_enabled_label",
        description_i18n_key: "settings_item_auth_register_activation_enabled_desc",
        value_type: "boolean",
        default_fn: || "true".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "user.registration_and_login",
        description: "Whether newly registered users must activate their account by email before signing in",
    },
    ConfigDef {
        key: "avatar_dir",
        label_i18n_key: "settings_item_avatar_dir_label",
        description_i18n_key: "settings_item_avatar_dir_desc",
        value_type: "string",
        default_fn: || crate::config::avatar::DEFAULT_AVATAR_DIR.to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "user.avatar",
        description: "Local directory used for uploaded avatar files (relative paths resolve under ./data)",
    },
    ConfigDef {
        key: "avatar_max_upload_size_bytes",
        label_i18n_key: "settings_item_avatar_max_upload_size_bytes_label",
        description_i18n_key: "settings_item_avatar_max_upload_size_bytes_desc",
        value_type: "number",
        default_fn: || crate::config::operations::DEFAULT_AVATAR_MAX_UPLOAD_SIZE_BYTES.to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "user.avatar",
        description: "Maximum avatar upload size in bytes before the request is rejected",
    },
    ConfigDef {
        key: "gravatar_base_url",
        label_i18n_key: "settings_item_gravatar_base_url_label",
        description_i18n_key: "settings_item_gravatar_base_url_desc",
        value_type: "string",
        default_fn: || "https://www.gravatar.com/avatar".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "user.avatar",
        description: "Gravatar avatar base URL (change to proxy/mirror if needed)",
    },
    // ── Audit ─────────────────────────────────────────────
    ConfigDef {
        key: "audit_log_enabled",
        label_i18n_key: "settings_item_audit_log_enabled_label",
        description_i18n_key: "settings_item_audit_log_enabled_desc",
        value_type: "boolean",
        default_fn: || "true".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "audit",
        description: "Enable or disable audit logging",
    },
    ConfigDef {
        key: "audit_log_retention_days",
        label_i18n_key: "settings_item_audit_log_retention_days_label",
        description_i18n_key: "settings_item_audit_log_retention_days_desc",
        value_type: "number",
        default_fn: || "90".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "audit",
        description: "Days before audit log entries are permanently deleted",
    },
    // ── Mail ──────────────────────────────────────────────
    ConfigDef {
        key: "mail_smtp_host",
        label_i18n_key: "settings_item_mail_smtp_host_label",
        description_i18n_key: "settings_item_mail_smtp_host_desc",
        value_type: "string",
        default_fn: String::new,
        requires_restart: false,
        is_sensitive: false,
        category: "mail.config",
        description: "SMTP server hostname used for transactional email delivery",
    },
    ConfigDef {
        key: "mail_smtp_port",
        label_i18n_key: "settings_item_mail_smtp_port_label",
        description_i18n_key: "settings_item_mail_smtp_port_desc",
        value_type: "number",
        default_fn: || "587".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "mail.config",
        description: "SMTP server port used for transactional email delivery",
    },
    ConfigDef {
        key: "mail_smtp_username",
        label_i18n_key: "settings_item_mail_smtp_username_label",
        description_i18n_key: "settings_item_mail_smtp_username_desc",
        value_type: "string",
        default_fn: String::new,
        requires_restart: false,
        is_sensitive: false,
        category: "mail.config",
        description: "SMTP username for authenticated mail delivery",
    },
    ConfigDef {
        key: "mail_smtp_password",
        label_i18n_key: "settings_item_mail_smtp_password_label",
        description_i18n_key: "settings_item_mail_smtp_password_desc",
        value_type: "string",
        default_fn: String::new,
        requires_restart: false,
        is_sensitive: true,
        category: "mail.config",
        description: "SMTP password for authenticated mail delivery",
    },
    ConfigDef {
        key: "mail_from_address",
        label_i18n_key: "settings_item_mail_from_address_label",
        description_i18n_key: "settings_item_mail_from_address_desc",
        value_type: "string",
        default_fn: String::new,
        requires_restart: false,
        is_sensitive: false,
        category: "mail.config",
        description: "From address used for account activation and contact verification email",
    },
    ConfigDef {
        key: "mail_from_name",
        label_i18n_key: "settings_item_mail_from_name_label",
        description_i18n_key: "settings_item_mail_from_name_desc",
        value_type: "string",
        default_fn: || "AsterDrive".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "mail.config",
        description: "Display name used for account activation and contact verification email",
    },
    ConfigDef {
        key: "mail_security",
        label_i18n_key: "settings_item_mail_security_label",
        description_i18n_key: "settings_item_mail_security_desc",
        value_type: "boolean",
        default_fn: || "true".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "mail.config",
        description: "Whether SMTP uses encryption. Port 465 uses implicit SSL/TLS; other ports use STARTTLS when enabled",
    },
    ConfigDef {
        key: "mail_template_register_activation_subject",
        label_i18n_key: "settings_item_mail_template_register_activation_subject_label",
        description_i18n_key: "settings_item_mail_template_register_activation_subject_desc",
        value_type: "string",
        default_fn: || {
            crate::config::mail::default_template_subject(
                crate::types::MailTemplateCode::RegisterActivation,
            )
            .to_string()
        },
        requires_restart: false,
        is_sensitive: false,
        category: "mail.template",
        description: "Subject template for registration activation emails",
    },
    ConfigDef {
        key: "mail_template_register_activation_html",
        label_i18n_key: "settings_item_mail_template_register_activation_html_label",
        description_i18n_key: "settings_item_mail_template_register_activation_html_desc",
        value_type: "multiline",
        default_fn: || {
            crate::config::mail::default_template_html(
                crate::types::MailTemplateCode::RegisterActivation,
            )
            .to_string()
        },
        requires_restart: false,
        is_sensitive: false,
        category: "mail.template",
        description: "HTML template for registration activation emails. Prefer a complete HTML document for best client compatibility",
    },
    ConfigDef {
        key: "mail_template_contact_change_confirmation_subject",
        label_i18n_key: "settings_item_mail_template_contact_change_confirmation_subject_label",
        description_i18n_key: "settings_item_mail_template_contact_change_confirmation_subject_desc",
        value_type: "string",
        default_fn: || {
            crate::config::mail::default_template_subject(
                crate::types::MailTemplateCode::ContactChangeConfirmation,
            )
            .to_string()
        },
        requires_restart: false,
        is_sensitive: false,
        category: "mail.template",
        description: "Subject template for email change confirmation emails",
    },
    ConfigDef {
        key: "mail_template_contact_change_confirmation_html",
        label_i18n_key: "settings_item_mail_template_contact_change_confirmation_html_label",
        description_i18n_key: "settings_item_mail_template_contact_change_confirmation_html_desc",
        value_type: "multiline",
        default_fn: || {
            crate::config::mail::default_template_html(
                crate::types::MailTemplateCode::ContactChangeConfirmation,
            )
            .to_string()
        },
        requires_restart: false,
        is_sensitive: false,
        category: "mail.template",
        description: "HTML template for email change confirmation emails. Prefer a complete HTML document for best client compatibility",
    },
    ConfigDef {
        key: "mail_template_password_reset_subject",
        label_i18n_key: "settings_item_mail_template_password_reset_subject_label",
        description_i18n_key: "settings_item_mail_template_password_reset_subject_desc",
        value_type: "string",
        default_fn: || {
            crate::config::mail::default_template_subject(
                crate::types::MailTemplateCode::PasswordReset,
            )
            .to_string()
        },
        requires_restart: false,
        is_sensitive: false,
        category: "mail.template",
        description: "Subject template for password reset emails",
    },
    ConfigDef {
        key: "mail_template_password_reset_html",
        label_i18n_key: "settings_item_mail_template_password_reset_html_label",
        description_i18n_key: "settings_item_mail_template_password_reset_html_desc",
        value_type: "multiline",
        default_fn: || {
            crate::config::mail::default_template_html(
                crate::types::MailTemplateCode::PasswordReset,
            )
            .to_string()
        },
        requires_restart: false,
        is_sensitive: false,
        category: "mail.template",
        description: "HTML template for password reset emails. Prefer a complete HTML document for best client compatibility",
    },
    ConfigDef {
        key: "mail_template_password_reset_notice_subject",
        label_i18n_key: "settings_item_mail_template_password_reset_notice_subject_label",
        description_i18n_key: "settings_item_mail_template_password_reset_notice_subject_desc",
        value_type: "string",
        default_fn: || {
            crate::config::mail::default_template_subject(
                crate::types::MailTemplateCode::PasswordResetNotice,
            )
            .to_string()
        },
        requires_restart: false,
        is_sensitive: false,
        category: "mail.template",
        description: "Subject template for password reset confirmation emails",
    },
    ConfigDef {
        key: "mail_template_password_reset_notice_html",
        label_i18n_key: "settings_item_mail_template_password_reset_notice_html_label",
        description_i18n_key: "settings_item_mail_template_password_reset_notice_html_desc",
        value_type: "multiline",
        default_fn: || {
            crate::config::mail::default_template_html(
                crate::types::MailTemplateCode::PasswordResetNotice,
            )
            .to_string()
        },
        requires_restart: false,
        is_sensitive: false,
        category: "mail.template",
        description: "HTML template for password reset confirmation emails. Prefer a complete HTML document for best client compatibility",
    },
    ConfigDef {
        key: "mail_template_contact_change_notice_subject",
        label_i18n_key: "settings_item_mail_template_contact_change_notice_subject_label",
        description_i18n_key: "settings_item_mail_template_contact_change_notice_subject_desc",
        value_type: "string",
        default_fn: || {
            crate::config::mail::default_template_subject(
                crate::types::MailTemplateCode::ContactChangeNotice,
            )
            .to_string()
        },
        requires_restart: false,
        is_sensitive: false,
        category: "mail.template",
        description: "Subject template for previous-address email change notices",
    },
    ConfigDef {
        key: "mail_template_contact_change_notice_html",
        label_i18n_key: "settings_item_mail_template_contact_change_notice_html_label",
        description_i18n_key: "settings_item_mail_template_contact_change_notice_html_desc",
        value_type: "multiline",
        default_fn: || {
            crate::config::mail::default_template_html(
                crate::types::MailTemplateCode::ContactChangeNotice,
            )
            .to_string()
        },
        requires_restart: false,
        is_sensitive: false,
        category: "mail.template",
        description: "HTML template for previous-address email change notices. Prefer a complete HTML document for best client compatibility",
    },
    // ── General ─────────────────────────────────────────────
    ConfigDef {
        key: "public_site_url",
        label_i18n_key: "settings_item_public_site_url_label",
        description_i18n_key: "settings_item_public_site_url_desc",
        value_type: "string",
        default_fn: String::new,
        requires_restart: false,
        is_sensitive: false,
        category: "general",
        description: "Public HTTP(S) site origin used when generating share, preview, and callback URLs",
    },
    ConfigDef {
        key: "branding_title",
        label_i18n_key: "settings_item_branding_title_label",
        description_i18n_key: "settings_item_branding_title_desc",
        value_type: "string",
        default_fn: || "AsterDrive".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "general",
        description: "Public browser title used by anonymous and authenticated pages",
    },
    ConfigDef {
        key: "branding_description",
        label_i18n_key: "settings_item_branding_description_label",
        description_i18n_key: "settings_item_branding_description_desc",
        value_type: "string",
        default_fn: || "Self-hosted cloud storage".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "general",
        description: "Public HTML description metadata exposed to anonymous pages",
    },
    ConfigDef {
        key: "branding_favicon_url",
        label_i18n_key: "settings_item_branding_favicon_url_label",
        description_i18n_key: "settings_item_branding_favicon_url_desc",
        value_type: "string",
        default_fn: || "/favicon.svg".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "general",
        description: "Public favicon URL applied at runtime for anonymous and authenticated pages",
    },
    ConfigDef {
        key: "branding_wordmark_dark_url",
        label_i18n_key: "settings_item_branding_wordmark_dark_url_label",
        description_i18n_key: "settings_item_branding_wordmark_dark_url_desc",
        value_type: "string",
        default_fn: || "/static/asterdrive/asterdrive-dark.svg".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "general",
        description: "Public site logo URL used on light surfaces such as headers and forms",
    },
    ConfigDef {
        key: "branding_wordmark_light_url",
        label_i18n_key: "settings_item_branding_wordmark_light_url_label",
        description_i18n_key: "settings_item_branding_wordmark_light_url_desc",
        value_type: "string",
        default_fn: || "/static/asterdrive/asterdrive-light.svg".to_string(),
        requires_restart: false,
        is_sensitive: false,
        category: "general",
        description: "Public site logo URL used on dark surfaces such as the login hero panel",
    },
    ConfigDef {
        key: crate::services::preview_app_service::PREVIEW_APPS_CONFIG_KEY,
        label_i18n_key: "settings_item_frontend_preview_apps_json_label",
        description_i18n_key: "settings_item_frontend_preview_apps_json_desc",
        value_type: "multiline",
        default_fn: crate::services::preview_app_service::default_public_preview_apps_json,
        requires_restart: false,
        is_sensitive: false,
        category: "general.preview",
        description: "Public preview app registry and matching rules used by the web frontend",
    },
];
