use utoipa::openapi::security::{ApiKey, ApiKeyValue, Http, HttpAuthScheme, SecurityScheme};
use utoipa::{Modify, OpenApi};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "AsterDrive API",
        version = env!("CARGO_PKG_VERSION"),
        description = "Self-hosted cloud storage API",
        license(name = "MIT"),
    ),
    modifiers(&SecurityAddon),
    paths(
        crate::api::routes::auth::check,
        crate::api::routes::auth::setup,
        crate::api::routes::auth::login,
        crate::api::routes::auth::register,
        crate::api::routes::auth::refresh,
        crate::api::routes::auth::logout,
        crate::api::routes::auth::me,
        crate::api::routes::auth::patch_preferences,
        crate::api::routes::auth::patch_profile,
        crate::api::routes::auth::upload_avatar,
        crate::api::routes::auth::put_avatar_source,
        crate::api::routes::auth::get_self_avatar,
        crate::api::routes::health::health,
        crate::api::routes::health::ready,
        crate::api::routes::files::upload,
        crate::api::routes::files::create_empty,
        crate::api::routes::files::get_file,
        crate::api::routes::files::download,
        crate::api::routes::files::get_thumbnail,
        crate::api::routes::files::delete_file,
        crate::api::routes::files::patch_file,
        crate::api::routes::files::init_chunked_upload,
        crate::api::routes::files::upload_chunk,
        crate::api::routes::files::complete_upload,
        crate::api::routes::files::presign_parts,
        crate::api::routes::files::get_upload_progress,
        crate::api::routes::files::cancel_upload,
        crate::api::routes::files::update_content,
        crate::api::routes::files::set_lock,
        crate::api::routes::files::copy_file,
        crate::api::routes::files::list_versions,
        crate::api::routes::files::restore_version,
        crate::api::routes::files::delete_version,
        crate::api::routes::folders::list_root,
        crate::api::routes::folders::create_folder,
        crate::api::routes::folders::list_folder,
        crate::api::routes::folders::get_ancestors,
        crate::api::routes::folders::delete_folder,
        crate::api::routes::folders::patch_folder,
        crate::api::routes::folders::set_lock,
        crate::api::routes::folders::copy_folder,
        crate::api::routes::admin::get_overview,
        crate::api::routes::admin::list_policies,
        crate::api::routes::admin::create_policy,
        crate::api::routes::admin::get_policy,
        crate::api::routes::admin::update_policy,
        crate::api::routes::admin::delete_policy,
        crate::api::routes::admin::test_policy_connection,
        crate::api::routes::admin::test_policy_params,
        crate::api::routes::admin::list_users,
        crate::api::routes::admin::create_user,
        crate::api::routes::admin::get_user,
        crate::api::routes::admin::update_user,
        crate::api::routes::admin::get_user_avatar,
        crate::api::routes::admin::list_user_policies,
        crate::api::routes::admin::assign_user_policy,
        crate::api::routes::admin::update_user_policy,
        crate::api::routes::admin::remove_user_policy,
        crate::api::routes::admin::list_config,
        crate::api::routes::admin::get_config,
        crate::api::routes::admin::set_config,
        crate::api::routes::admin::delete_config,
        crate::api::routes::admin::list_all_shares,
        crate::api::routes::admin::admin_delete_share,
        crate::api::routes::admin::list_locks,
        crate::api::routes::admin::force_unlock,
        crate::api::routes::admin::cleanup_expired_locks,
        crate::api::routes::admin::list_audit_logs,
        crate::api::routes::admin::config_schema,
        crate::api::routes::admin::force_delete_user,
        // search
        crate::api::routes::search::search,
        // batch
        crate::api::routes::batch::batch_delete,
        crate::api::routes::batch::batch_move,
        crate::api::routes::batch::batch_copy,
        // shares (authenticated)
        crate::api::routes::shares::create_share,
        crate::api::routes::shares::list_shares,
        crate::api::routes::shares::delete_share,
        // trash
        crate::api::routes::trash::list_trash,
        crate::api::routes::trash::restore,
        crate::api::routes::trash::purge_one,
        crate::api::routes::trash::purge_all,
        // webdav accounts
        crate::api::routes::webdav_accounts::list_accounts,
        crate::api::routes::webdav_accounts::get_settings,
        crate::api::routes::webdav_accounts::create_account,
        crate::api::routes::webdav_accounts::delete_account,
        crate::api::routes::webdav_accounts::toggle_account,
        crate::api::routes::webdav_accounts::test_connection,
        // properties
        crate::api::routes::properties::list_props,
        crate::api::routes::properties::set_prop,
        crate::api::routes::properties::delete_prop,
        // shares (public)
        crate::api::routes::share_public::get_share_info,
        crate::api::routes::share_public::verify_password,
        crate::api::routes::share_public::download_shared,
        crate::api::routes::share_public::download_shared_folder_file,
        crate::api::routes::share_public::list_shared_content,
        crate::api::routes::share_public::list_shared_subfolder_content,
        crate::api::routes::share_public::shared_avatar,
        crate::api::routes::share_public::shared_thumbnail,
        crate::api::routes::share_public::shared_folder_file_thumbnail,
    ),
    components(
        schemas(
            crate::api::error_code::ErrorCode,
            crate::api::pagination::SortBy,
            crate::api::pagination::SortOrder,
            crate::api::pagination::LimitOffsetQuery,
            crate::api::pagination::OffsetPage<crate::entities::audit_log::Model>,
            crate::api::pagination::OffsetPage<crate::services::user_service::UserInfo>,
            crate::api::pagination::OffsetPage<crate::entities::storage_policy::Model>,
            crate::api::pagination::OffsetPage<crate::entities::user_storage_policy::Model>,
            crate::api::pagination::OffsetPage<crate::entities::share::Model>,
            crate::api::pagination::OffsetPage<crate::services::share_service::MyShareInfo>,
            crate::api::pagination::OffsetPage<crate::entities::system_config::Model>,
            crate::api::pagination::OffsetPage<crate::entities::resource_lock::Model>,
            crate::api::pagination::OffsetPage<crate::services::webdav_account_service::WebdavAccountInfo>,
            crate::services::admin_service::AdminOverview,
            crate::services::admin_service::AdminOverviewStats,
            crate::services::admin_service::AdminOverviewDailyReport,
            crate::services::folder_service::FolderContents,
            crate::services::folder_service::FolderAncestorItem,
            crate::api::response::HealthResponse,
            crate::api::response::MemoryStatsResponse,
            crate::api::response::PurgedCountResponse,
            crate::api::response::RemovedCountResponse,
            crate::entities::file::Model,
            crate::entities::folder::Model,
            crate::entities::storage_policy::Model,
            crate::types::UserRole,
            crate::types::UserStatus,
            crate::types::AvatarSource,
            crate::types::DriverType,
            crate::api::routes::auth::CheckReq,
            crate::api::routes::auth::CheckResp,
            crate::api::routes::auth::SetupReq,
            crate::api::routes::auth::RegisterReq,
            crate::api::routes::auth::LoginReq,
            crate::services::user_service::UserCore,
            crate::services::user_service::UserInfo,
            crate::services::user_service::MeResponse,
            crate::services::user_service::ThemeMode,
            crate::services::user_service::ColorPreset,
            crate::services::user_service::PrefViewMode,
            crate::services::user_service::Language,
            crate::services::user_service::UserPreferences,
            crate::services::user_service::UpdatePreferencesReq,
            crate::services::profile_service::AvatarInfo,
            crate::services::profile_service::UserProfileInfo,
            crate::api::routes::auth::UpdateProfileReq,
            crate::api::routes::auth::UpdateAvatarSourceReq,
            crate::api::routes::files::FileQuery,
            crate::api::routes::files::PatchFileReq,
            crate::api::routes::folders::CreateFolderReq,
            crate::api::routes::folders::PatchFolderReq,
            crate::api::routes::folders::SetLockReq,
            crate::api::routes::files::SetLockReq,
            crate::api::routes::files::CopyFileReq,
            crate::api::routes::folders::CopyFolderReq,
            crate::entities::file_version::Model,
            crate::api::routes::admin::CreatePolicyReq,
            crate::api::routes::admin::PatchPolicyReq,
            crate::api::routes::admin::CreateUserReq,
            crate::api::routes::admin::PatchUserReq,
            crate::api::routes::admin::AssignUserPolicyReq,
            crate::api::routes::admin::PatchUserPolicyReq,
            crate::api::routes::admin::TestPolicyParamsReq,
            crate::api::routes::admin::SetConfigReq,
            crate::entities::system_config::Model,
            crate::entities::user_storage_policy::Model,
            crate::entities::share::Model,
            crate::services::share_service::MyShareInfo,
            crate::services::share_service::ShareStatus,
            crate::services::share_service::SharePublicOwnerInfo,
            crate::services::share_service::SharePublicInfo,
            crate::api::routes::shares::CreateShareReq,
            crate::api::routes::share_public::VerifyPasswordReq,
            crate::api::routes::files::InitUploadReq,
            crate::api::routes::files::CompleteUploadReq,
            crate::api::routes::files::CompletedPartReq,
            crate::api::routes::files::PresignPartsReq,
            crate::entities::upload_session::Model,
            crate::services::upload_service::InitUploadResponse,
            crate::services::upload_service::ChunkUploadResponse,
            crate::services::upload_service::UploadProgressResponse,
            crate::entities::webdav_account::Model,
            crate::services::webdav_account_service::WebdavAccountCreated,
            crate::services::webdav_account_service::WebdavAccountInfo,
            crate::api::routes::webdav_accounts::WebdavSettingsInfo,
            crate::api::routes::webdav_accounts::CreateWebdavAccountReq,
            crate::services::trash_service::TrashContents,
            crate::services::trash_service::TrashFileItem,
            crate::services::trash_service::TrashFolderItem,
            crate::api::routes::trash::TrashItemPath,
            crate::api::routes::webdav_accounts::TestConnectionReq,
            crate::entities::entity_property::Model,
            crate::entities::resource_lock::Model,
            crate::api::routes::properties::SetPropReq,
            // audit log
            crate::entities::audit_log::Model,
            // search
            crate::db::repository::search_repo::FileSearchItem,
            crate::services::search_service::SearchParams,
            crate::services::search_service::SearchResults,
            // batch
            crate::api::routes::batch::BatchDeleteReq,
            crate::api::routes::batch::BatchMoveReq,
            crate::api::routes::batch::BatchCopyReq,
            crate::services::batch_service::BatchResult,
            crate::services::batch_service::BatchItemError,
        ),
    ),
    tags(
        (name = "auth", description = "Authentication"),
        (name = "files", description = "File operations"),
        (name = "folders", description = "Folder operations"),
        (name = "admin", description = "Admin operations"),
        (name = "shares", description = "File/folder sharing"),
        (name = "trash", description = "Recycle bin"),
        (name = "webdav", description = "WebDAV account management"),
        (name = "properties", description = "Entity properties"),
        (name = "health", description = "Health checks"),
        (name = "search", description = "Search files and folders"),
        (name = "batch", description = "Batch operations"),
    ),
)]
pub struct ApiDoc;

/// 注册 Cookie + Bearer 两种认证方式到 OpenAPI security schemes
struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_with(Default::default);
        // "bearer" 匹配 utoipa actix_extras 从 JwtAuth 中间件自动推断的 scheme 名
        components.add_security_scheme(
            "bearer",
            SecurityScheme::Http(Http::new(HttpAuthScheme::Bearer)),
        );
        components.add_security_scheme(
            "cookie_auth",
            SecurityScheme::ApiKey(ApiKey::Cookie(ApiKeyValue::new("aster_access"))),
        );
    }
}
