use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "AsterDrive API",
        version = env!("CARGO_PKG_VERSION"),
        description = "Self-hosted cloud storage API",
        license(name = "MIT"),
    ),
    paths(
        crate::api::routes::auth::login,
        crate::api::routes::auth::register,
        crate::api::routes::auth::refresh,
        crate::api::routes::auth::logout,
        crate::api::routes::auth::me,
        crate::api::routes::health::health,
        crate::api::routes::health::ready,
        crate::api::routes::files::upload,
        crate::api::routes::files::get_file,
        crate::api::routes::files::download,
        crate::api::routes::files::delete_file,
        crate::api::routes::files::patch_file,
        crate::api::routes::files::init_chunked_upload,
        crate::api::routes::files::upload_chunk,
        crate::api::routes::files::complete_upload,
        crate::api::routes::files::get_upload_progress,
        crate::api::routes::files::cancel_upload,
        crate::api::routes::folders::list_root,
        crate::api::routes::folders::create_folder,
        crate::api::routes::folders::list_folder,
        crate::api::routes::folders::delete_folder,
        crate::api::routes::folders::patch_folder,
        crate::api::routes::admin::list_policies,
        crate::api::routes::admin::create_policy,
        crate::api::routes::admin::get_policy,
        crate::api::routes::admin::update_policy,
        crate::api::routes::admin::delete_policy,
        crate::api::routes::admin::list_users,
        crate::api::routes::admin::get_user,
        crate::api::routes::admin::update_user,
        crate::api::routes::admin::list_user_policies,
        crate::api::routes::admin::assign_user_policy,
        crate::api::routes::admin::update_user_policy,
        crate::api::routes::admin::remove_user_policy,
        crate::api::routes::admin::list_config,
        crate::api::routes::admin::get_config,
        crate::api::routes::admin::set_config,
        crate::api::routes::admin::delete_config,
        crate::api::routes::admin::list_all_shares,
        crate::api::routes::admin::admin_delete_share,
        // shares (authenticated)
        crate::api::routes::shares::create_share,
        crate::api::routes::shares::list_shares,
        crate::api::routes::shares::delete_share,
        // shares (public)
        crate::api::routes::share_public::get_share_info,
        crate::api::routes::share_public::verify_password,
        crate::api::routes::share_public::download_shared,
        crate::api::routes::share_public::list_shared_content,
    ),
    components(
        schemas(
            crate::api::error_code::ErrorCode,
            crate::api::response::TokenResponse,
            crate::api::response::RefreshResponse,
            crate::api::response::FolderContentsResponse,
            crate::api::response::HealthResponse,
            crate::entities::user::Model,
            crate::entities::file::Model,
            crate::entities::folder::Model,
            crate::entities::storage_policy::Model,
            crate::types::UserRole,
            crate::types::UserStatus,
            crate::types::DriverType,
            crate::api::routes::auth::RegisterReq,
            crate::api::routes::auth::LoginReq,
            crate::api::routes::files::FileQuery,
            crate::api::routes::files::PatchFileReq,
            crate::api::routes::folders::CreateFolderReq,
            crate::api::routes::folders::PatchFolderReq,
            crate::api::routes::admin::CreatePolicyReq,
            crate::api::routes::admin::PatchPolicyReq,
            crate::api::routes::admin::PatchUserReq,
            crate::api::routes::admin::AssignUserPolicyReq,
            crate::api::routes::admin::PatchUserPolicyReq,
            crate::api::routes::admin::SetConfigReq,
            crate::entities::system_config::Model,
            crate::entities::user_storage_policy::Model,
            crate::entities::share::Model,
            crate::services::share_service::SharePublicInfo,
            crate::api::routes::shares::CreateShareReq,
            crate::api::routes::share_public::VerifyPasswordReq,
            crate::api::routes::files::InitUploadReq,
            crate::entities::upload_session::Model,
            crate::services::upload_service::InitUploadResponse,
            crate::services::upload_service::ChunkUploadResponse,
            crate::services::upload_service::UploadProgressResponse,
        ),
    ),
    tags(
        (name = "auth", description = "Authentication"),
        (name = "files", description = "File operations"),
        (name = "folders", description = "Folder operations"),
        (name = "admin", description = "Admin operations"),
        (name = "shares", description = "File/folder sharing"),
        (name = "health", description = "Health checks"),
    ),
)]
pub struct ApiDoc;
